<?php

namespace ContainerZho6P1U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7jd6e_OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7jd6e.O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7jd6e.O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CarController::add' => ['privates', '.service_locator.axWvN5H.App\\Controller\\CarController::add()', 'getCarControlleraddService', true],
            'App\\Controller\\UserController::create' => ['privates', '.service_locator.qxrAMgr.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.FAUiyCT.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CarController:add' => ['privates', '.service_locator.axWvN5H.App\\Controller\\CarController::add()', 'getCarControlleraddService', true],
            'App\\Controller\\UserController:create' => ['privates', '.service_locator.qxrAMgr.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.FAUiyCT.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CarController::add' => '?',
            'App\\Controller\\UserController::create' => '?',
            'App\\Controller\\UserController::update' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CarController:add' => '?',
            'App\\Controller\\UserController:create' => '?',
            'App\\Controller\\UserController:update' => '?',
        ]);
    }
}
