<?php

namespace ContainerZho6P1U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_EncryptionDumpFieldsMapService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_mongodb.odm.command.encryption_dump_fields_map' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\Encryption\DumpFieldsMapCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/src/Command/Encryption/DumpFieldsMapCommand.php';

        $container->privates['doctrine_mongodb.odm.command.encryption_dump_fields_map'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\Encryption\DumpFieldsMapCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine_mongodb.odm.default_document_manager' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
        ], [
            'doctrine_mongodb.odm.default_document_manager' => 'Doctrine\\ODM\\MongoDB\\DocumentManager',
        ]));

        $instance->setName('doctrine:mongodb:encryption:dump-fields-map');
        $instance->setDescription('Dumps the encrypted fields map for all documents in the configured connections.');

        return $instance;
    }
}
