<?php

namespace ContainerZho6P1U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublishTripControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PublishTripController' shared autowired service.
     *
     * @return \App\Controller\PublishTripController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PublishTripController.php';

        $container->services['App\\Controller\\PublishTripController'] = $instance = new \App\Controller\PublishTripController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\PublishTripController', $container));

        return $instance;
    }
}
