<?php

namespace ContainerZho6P1U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qxrAMgr.App\Controller\UserController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qxrAMgr.App\\Controller\\UserController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'validator', 'getValidatorService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'validator' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UserController::create()', $container);
    }
}
