<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZho6P1U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZho6P1U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZho6P1U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZho6P1U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZho6P1U\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zho6P1U',
    'container.build_id' => 'eaf1c202',
    'container.build_time' => 1760368344,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZho6P1U');
