<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIEv37w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIEv37w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIEv37w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIEv37w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOIEv37w\App_KernelDevDebugContainer([
    'container.build_hash' => 'OIEv37w',
    'container.build_id' => '5f03b18d',
    'container.build_time' => 1758628219,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIEv37w');
